version: 0.2

env:
  variables:
    REGION: "us-west-1"  # Replace with your AWS region

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install awscli

  pre_build:
    commands:
      - echo Fetching full Git history...
      - git fetch --unshallow || true
      - echo Identifying changed Lambda directories...
      - |
        # Identify directories with changes under 'lambda-function'
        changed_dirs=$(git diff --name-only origin/main...HEAD | grep '^web/lambda-function/[^/]\+/lambda_function.py$' | cut -d'/' -f3 | sort | uniq)
        echo "Changed directories: $changed_dirs"
        if [ -z "$changed_dirs" ]; then
          echo "No Lambda functions have changed."
          exit 0
        fi
      - echo "Changed Lambda directories identified."

  build:
    commands:
      - echo Packaging and deploying changed Lambda functions...
      - |
        for dir in $changed_dirs; do
          echo "Deploying Lambda function in directory: $dir"
          cd "web/lambda-function/$dir" || continue
          zip -r "/tmp/$dir.zip" .
          aws lambda update-function-code --function-name "$dir" --zip-file fileb:///tmp/$dir.zip --region "$REGION"
          cd - > /dev/null
        done
      - echo "Deployment completed for changed Lambda functions."

artifacts:
  files:
    - '**/*'
