version: 0.2

phases:
  install:
    commands:
      - echo "==================== INSTALL PHASE ===================="
      - echo "Updating system and installing dependencies..."
      - apt-get update && apt-get install -y jq
      - echo "Installation complete."

  pre_build:
    commands:
      - echo "==================== PRE-BUILD PHASE ===================="
      - echo "Fetching commit ID from CodeBuild environment..."
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - export COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Commit ID: $COMMIT_ID"

      - echo "Fetching changed files..."
      - ls -R > files_list.txt
      - cat files_list.txt

      - echo "Extracting unique repositories..."
      - find . -type f | awk -F'/' '{print $1}' | sort -u > repo_names.txt
      - echo "Unique Repositories Found:"
      - cat repo_names.txt

  build:
    commands:
      - echo "==================== BUILD PHASE ===================="
      - echo "No Lambda updates for now. Just verifying repo detection."
      - echo "Debugging environment variables..."
      - env | sort

  post_build:
    commands:
      - echo "==================== POST-BUILD PHASE ===================="
      - echo "Build completed successfully!"
