version: 0.2

phases:
  build:
    commands:
      # Get the changed folder name (assuming one folder per commit)
      - CHANGED_FOLDER=$(git diff --name-only HEAD^ HEAD | cut -d'/' -f1 | uniq)
      - echo "Updating Lambda: $CHANGED_FOLDER"

      # Zip the folder
      - cd "$CHANGED_FOLDER" && zip -r "../$CHANGED_FOLDER.zip" .
      - cd ..

      # Update Lambda (function name = folder name)
      - aws lambda update-function-code \
          --function-name "$CHANGED_FOLDER" \
          --zip-file "fileb://$CHANGED_FOLDER.zip"
