version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: your-secret-id:GITHUB_TOKEN  # 🔒 Only secret you provide

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "🔎 Deriving repo owner, name and PR number…"
      - REPO_URL="${CODEBUILD_SOURCE_REPO_URL:-$(git config --get remote.origin.url)}"
      - echo "Repo URL: $REPO_URL"
      - REPO_PATH=${REPO_URL#*github.com[:/]}
      - REPO_PATH=${REPO_PATH%.git}
      - REPO_OWNER=$(echo "$REPO_PATH" | cut -d/ -f1)
      - REPO_NAME=$(echo "$REPO_PATH" | cut -d/ -f2)
      - |
        if [[ "$CODEBUILD_SOURCE_VERSION" =~ ^pr/([0-9]+)$ ]]; then
          PR_NUMBER="${BASH_REMATCH[1]}"
        fi
      - echo "Owner: $REPO_OWNER  Repo: $REPO_NAME  PR: ${PR_NUMBER:-none}"

  build:
    commands:
      - echo "🧪 Checking syntax for khajum.py…"
      - |
        if ! python -m py_compile khajum.py; then
          echo "Syntax error in khajum.py!"
          export CODEBUILD_BUILD_SUCCEEDING=0
        fi

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ] && [ -n "$PR_NUMBER" ]; then
          echo "❌ Build failed – closing PR #$PR_NUMBER"
          curl -s -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PR_NUMBER}" \
            -d '{"state":"closed"}'
        else
          echo "✅ Build passed – no action needed."
        fi
