version: 0.2

env:
  variables:
    LAMBDA_NAME: "Testing_CICD"  # Set in CodeBuild environment

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Fetching changed files..."
      - git fetch origin main  # Ensure latest commit history
      - CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')  # Get modified files in one line
      - echo "Modified files: $CHANGED_FILES"

  build:
    commands:
      - echo "Checking if there are files to update..."
      - |
        if [ -z "$CHANGED_FILES" ]; then
          echo "No files changed. Skipping deployment.";
          exit 0;
        else
          echo "Zipping only changed files...";
          zip lambda_function.zip $CHANGED_FILES;
          echo "Updating Lambda function: $LAMBDA_NAME";
          aws lambda update-function-code --function-name "$LAMBDA_NAME" --zip-file fileb://lambda_function.zip;
        fi

  post_build:
    commands:
      - echo "Lambda function $LAMBDA_NAME updated successfully!"
