version: 0.2

env:
  variables:
    REGION: us-west-1

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  pre_build:
    commands:
      - echo "Collecting changed lambda folders..."
      # Ensure we fetch enough Git history if needed
      - git fetch --unshallow || true
      # Find changed lambda_function.py files
      - |
        git diff --name-only origin/main...HEAD | grep '^web/lambda-function/.*/lambda_function.py$' | cut -d'/' -f3 | sort | uniq > changed-lambdas.txt
      - echo "Changed Lambdas:"
      - cat changed-lambdas.txt || echo "No Lambda functions changed."

  build:
    commands:
      - |
        if [ ! -s changed-lambdas.txt ]; then
          echo "No Lambda changes to deploy."
        else
          while read lambda_folder; do
            echo "Packaging and deploying $lambda_folder"
            cd web/lambda-function/$lambda_folder || continue
            zip -r /tmp/$lambda_folder.zip .
            cd - > /dev/null
            aws lambda update-function-code \
              --function-name "$lambda_folder" \
              --zip-file fileb:///tmp/$lambda_folder.zip \
              --region "$REGION"
          done < changed-lambdas.txt
        fi
