version: 0.2

phases:
  build:
    commands:
      - echo "Checking syntax for try.py..."
      - python -m py_compile try.py
      - echo "Syntax check passed. Running try.py..."
      - python khajum.py
