version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      - echo "Fetching commit ID from CodeBuild environment..."
      - export COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Commit ID: $COMMIT_ID"

      - echo "Fetching changed files from CodePipeline..."
      - ls -R > files_list.txt
      - cat files_list.txt

      - echo "Extracting unique repositories..."
      - find . -type f | awk -F'/' '{print $2}' | sort -u > repo_names.txt
      - cat repo_names.txt

  build:
    commands:
      - echo "No Lambda updates for now. Just verifying repo detection."

  post_build:
    commands:
      - echo "Build completed successfully!"
