version: 0.2

phases:
  build:
    commands:
      - echo "Detecting changed folder..."
      - CHANGED_FOLDER=$(git diff --name-only HEAD^ HEAD | cut -d'/' -f1 | sort | uniq | head -n 1)
      - echo "Changed folder: $CHANGED_FOLDER"
      - cd "$CHANGED_FOLDER"
      - zip -r "../$CHANGED_FOLDER.zip" .
      - cd ..
      - echo "Updating Lambda function: $CHANGED_FOLDER"
      - aws lambda update-function-code --function-name "$CHANGED_FOLDER" --zip-file "fileb://$CHANGED_FOLDER.zip"
