version: 0.2

env:
  variables:
    REGION: us-west-1

phases:
  install:
    commands:
      - apt-get update && apt-get install -y zip

  pre_build:
    commands:
      - git diff --name-only HEAD~1 HEAD > changed_files.txt
      - export CHANGED_LAMBDAS=$(cat changed_files.txt | grep '^lambda-functions/' | cut -d '/' -f2 | sort -u)
      - echo "Changed Lambda folders: $CHANGED_LAMBDAS"

  build:
    commands: |
      for dir in $CHANGED_LAMBDAS; do
        echo "Deploying Lambda function: $dir"
        cd lambda-functions/$dir
        zip -r /tmp/$dir.zip .
        cd ../../
        aws lambda update-function-code \
          --function-name "$dir" \
          --zip-file fileb:///tmp/$dir.zip \
          --region "$REGION"
      done
