version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - lambda_function.zip
