version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install terraform -y
      - terraform version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Importing existing resources...
      - echo Running Terraform Plan...
      - terraform import aws_db_instance.vivint_store_instance vivint-store-instance-1
      - terraform plan
      - echo Applying Terraform changes...
      - terraform apply -auto-approve
