version: 0.2

phases:
  install:
    commands:
      - npm install
      - composer install
  pre_build:
    commands:
      # Any pre-build commands if neededs
  build:
    commands:
      - npm run build
  post_build:
    commands:

artifacts:
  files:
      - '**/*'
