version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building Lambda deployment package..."
      # Replace the following with your build commands, such as compiling code, running tests, etc.
      - echo "Build commands go here"

  post_build:
    commands:
      - echo "Deploying to Lambda..."
      # AWS Lambda deployment command
      - aws lambda update-function-code --function-name lambda-testing --zip-file fileb://lambda.zip --region us-west-1
      # You may need to add additional configuration options such as role ARN, if necessary
