Stages:
  - Name: Source
    Actions:
      - Name: SourceCode
        ActionTypeId:
          Category: Source
          Owner: khajum7
          Provider: GitHub
          Version: 1
        Configuration:
          Owner: khajum7
          Repo: web
          Branch: main
          OAuthToken: YOUR_GITHUB_TOKEN
          PollForSourceChanges: true
        OutputArtifacts:
          - Name: SourceOutput

  # Optional build stage
  - Name: Build
    Actions:
      - Name: BuildAction
        ActionTypeId:
          Category: Build
          Owner: AWS
          Provider: CodeBuild
          Version: 1
        Configuration:
          ProjectName: CICD-testing
        InputArtifacts:
          - Name: SourceOutput
        OutputArtifacts:
          - Name: BuildOutput

  - Name: Deploy
    Actions:
      - Name: DeployToLambda
        ActionTypeId:
          Category: Deploy
          Owner: AWS
          Provider: Lambda
          Version: 1
        Configuration:
          FunctionName: lambda-testing
          ActionMode: Replace
          RoleArn: arn:aws:lambda:us-west-1:177453828722:function:lambda-testing
          InputArtifacts:
            - Name: SourceOutput
        RunOrder: 1
