version: 0.2

phases:
  pre_build:
    commands:
      - echo Detecting changed folders...
      - git fetch --unshallow || true
      - git diff --name-only HEAD~1 > changed_files.txt || echo "" > changed_files.txt
      - cat changed_files.txt
      - |
        export CHANGED_DIRS=$(cut -d/ -f1 changed_files.txt | sort | uniq)
        echo "Detected changed folders: $CHANGED_DIRS"

  build:
    commands:
      - for DIR in $CHANGED_DIRS; do
          echo "Packaging and deploying $DIR...";
          if [ -d "$DIR" ]; then
            cd $DIR;
            zip -r ../${DIR}.zip .;
            cd ..;
            aws lambda update-function-code --function-name $DIR --zip-file fileb://${DIR}.zip;
          else
            echo "Directory $DIR not found, skipping.";
          fi
        done

artifacts:
  files:
    - changed_files.txt
