version: 0.2

env:
  variables:
    LAMBDA_NAME: "Testing_CICD"  # Change this or set in CodeBuild environment

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Checking for updates in GitHub repository..."
      - echo "Latest commit: $COMMIT_ID"

  build:
    commands:
      - echo "Zipping source files..."
      - zip -r lambda_function.zip . -x "*.git*" "README.md" "buildspec.yml"
      
      - echo "Updating Lambda function: $LAMBDA_NAME"
      - aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://lambda_function.zip

  post_build:
    commands:
      - echo "Lambda function $LAMBDA_NAME updated successfully!"
